# Vibe Coding Configuration
# Configuración principal del flujo de trabajo Vibe Coding

# Configuración de rutas del proyecto
project:
  name: brainstorm_conectatech
  version: 1.0.0
  root_dir: .
  src_dir: src
  tests_dir: tests
  docs_dir: docs
  scripts_dir: scripts

# Configuración de documentación
documentation:
  enabled: true
  output_dir: docs
  include_examples: true
  validate_docstrings: true
  required_sections:
    - "Args"
    - "Returns"
    - "Raises"
    - "Examples"

# Configuración de pruebas
testing:
  framework: pytest
  coverage_threshold: 80
  test_pattern: "test_*.py"
  integration_test_dir: tests/integration
  unit_test_dir: tests/unit

# Configuración de estilo de código
code_style:
  formatter: black
  line_length: 88
  use_double_quotes: true
  include_trailing_comma: true
  python_version: "3.10"

# Configuración de IA (ajustar según sea necesario)
ai:
  default_model: "gpt-4"
  temperature: 0.2
  max_tokens: 2000
  code_review_model: "gpt-4"
  test_generation_model: "gpt-4"

# Configuración de integración continua
ci:
  enabled: true
  skip_dirty: false
  pre_commit_hooks: true
  validate_commits: true

# Configuración de despliegue
deployment:
  package_manager: pip
  python_version: "3.10"
  requirements_files:
    - "requirements.txt"
    - "requirements-dev.txt"

# Configuración de logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  datefmt: "%Y-%m-%d %H:%M:%S"
  file: "logs/vibe_coding.log"

# Configuración de seguridad
security:
  secret_key: ${SECRET_KEY}
  allowed_hosts:
    - "localhost"
    - "127.0.0.1"
  debug: false

# Configuración de la base de datos
database:
  engine: "postgresql"
  name: "brainstorm_db"
  user: "postgres"
  password: "${DB_PASSWORD}"
  host: "localhost"
  port: 5432
  pool_size: 5
  max_overflow: 10

# Configuración de la API
api:
  title: "Brainstorm ConectaTech API"
  description: "API para el sistema Brainstorm de ConectaTech"
  version: "1.0.0"
  docs_url: "/docs"
  redoc_url: "/redoc"
  openapi_url: "/openapi.json"

# Plantillas para generación de código
templates:
  module: "templates/module"
  api_route: "templates/api/route.py"
  model: "templates/models/model.py"
  test: "templates/tests/test_template.py"

# Configuración de herramientas de desarrollo
dev_tools:
  pre_commit: true
  mypy: true
  flake8: true
  black: true
  isort: true
  pytest: true
  coverage: true

# Configuración de notificaciones
notifications:
  email:
    enabled: false
    smtp_server: "smtp.example.com"
    smtp_port: 587
    sender: "noreply@conectatech.com"
  slack:
    enabled: true
    webhook_url: "${SLACK_WEBHOOK_URL}"
    channel: "#brainstorm-dev"
